# 1. Create netlify.toml in your project root
[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

# 2. Deploy to Netlify
- Connect your GitHub repo
- Or drag & drop your folder
- Site will be live!
